"""hOn OAuth login flow - PURE pieces (addhOn transport).

Deterministic pieces of the login flow:
- `build_authorize_url(nonce)`: the Salesforce authorize URL;
- `is_oauth_done(text)` / `extract_login_url(text)`: the parsing of the authorize page.

The URL and the "by hand" encoding of the parameters (scope with NON encoded spaces,
pre-quoted `redirect_uri`) are the contract the server expects, so they are built
exactly. Constants are inline (like the other transport modules). The HTTP
orchestration that uses these pieces lives in the session/auth.
"""
from __future__ import annotations

import json
import re
import secrets
from typing import Any
from urllib.parse import quote, unquote

# Endpoints/identifiers of the hOn cloud.
AUTH_API = "https://account2.hon-smarthome.com"
APP = "hon"
CLIENT_ID = (
    "3MVG9QDx8IX8nP5T2Ha8ofvlmjLZl5L_gvfbT9."
    "HJvpHGKoAS_dcMN8LYpTSYeVFCraUnV.2Ag1Ki7m4znVO6"
)

# Extracts the first `url='...'` or `href='...'` link from the authorize page.
_LOGIN_URL_RE = re.compile("(?:url|href) ?= ?'(.+?)'")


def build_authorize_url(nonce: str) -> str:
    """OAuth authorize URL (mobile login). `nonce` generated by the caller."""
    redirect_uri = quote(f"{APP}://mobilesdk/detect/oauth/done")
    params = {
        "response_type": "token+id_token",
        "client_id": CLIENT_ID,
        "redirect_uri": redirect_uri,
        "display": "touch",
        "scope": "api openid refresh_token web",
        "nonce": nonce,
    }
    # "By hand" join: NO urlencode (scope keeps the spaces).
    query = "&".join(f"{k}={v}" for k, v in params.items())
    return f"{AUTH_API}/services/oauth2/authorize/expid_Login?{query}"


def is_oauth_done(text: str) -> bool:
    """True if the authorize page is ALREADY the redirect with the tokens (login not needed).

    PRECEDENCE for the orchestration: call `extract_login_url` FIRST; consult
    `is_oauth_done` ONLY if the extraction returns None (if a login_url is found, the
    presence of oauth/done is ignored).
    """
    return "oauth/done#access_token=" in text


def extract_login_url(text: str) -> str | None:
    """Login URL from the authorize page, or None if absent.

    The relative `/NewhOnLogin...` (new login page since Jul-2024) is rewritten
    to the old endpoint `/s/login...` to avoid the new page.
    """
    matches = _LOGIN_URL_RE.findall(text)
    if not matches:
        return None
    url = matches[0]
    if url.startswith("/NewhOnLogin"):
        url = f"{AUTH_API}/s/login{url}"
    return url


def generate_nonce() -> str:
    """Nonce in 8-4-4-4-12 format."""
    nonce = secrets.token_hex(16)
    return f"{nonce[:8]}-{nonce[8:12]}-{nonce[12:16]}-{nonce[16:20]}-{nonce[20:]}"


def build_login_payload(
    email: str, password: str, fw_uid: str, loaded: Any, page_url: str
) -> tuple[str, dict[str, Any]]:
    """(body, params) of the Salesforce login POST (/s/sfsites/aura).

    The aura shape and the encoding `&`.join(f"{k}={quote(json.dumps(v))}") are the
    server contract (key order included), so the body is built exactly.
    """
    start_url = page_url.rsplit("startURL=", maxsplit=1)[-1]
    start_url = unquote(start_url).split("%3D")[0]
    action = {
        "id": "79;a",
        "descriptor": "apex://LightningLoginCustomController/ACTION$login",
        "callingDescriptor": "markup://c:loginForm",
        "params": {"username": email, "password": password, "startUrl": start_url},
    }
    data = {
        "message": {"actions": [action]},
        "aura.context": {
            "mode": "PROD",
            "fwuid": fw_uid,
            "app": "siteforce:loginApp2",
            "loaded": loaded,
            "dn": [],
            "globals": {},
            "uad": False,
        },
        "aura.pageURI": page_url,
        "aura.token": None,
    }
    body = "&".join(f"{k}={quote(json.dumps(v))}" for k, v in data.items())
    params: dict[str, Any] = {"r": 3, "other.LightningLoginCustom.login": 1}
    return body, params
